import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import { useState } from "react";
import Modal from "./modal";
import Link from "next/link";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [modal, setModal] = useState(false);

  const handleDarkMode = () => {
    setDarkMode(!darkMode);
  };

  const handleModal = () => {
    setModal(!modal);
  };

  return (
    <>
      <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Danial Zahidi Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="bg-gray-100 mx-auto dark:bg-black">
          <section className="min-h-screen">
            <nav className="py-5  flex justify-between px-1 lg:px-10 bg-slate-700 dark:bg-black">
              <h1 className="text-xl font-mono dark:text-gray-400">thisis<span className="text-red-500">danial</span></h1>
              <ul className="flex items-center">
                <li>
                  <BsFillMoonStarsFill
                    onClick={handleDarkMode}
                    className="cursor-pointer text-2xl dark:text-white"
                  />
                </li>
                <li>
                  <a 
                    className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                    href="#"
                  >
                    Resume
                  </a>
                </li>
              </ul>
            </nav>

            <div className="grid items-center justify-center md:p-auto lg:p-10">
              <div className="">
                <h2 className="text-5xl text-teal-600 font-medium md:text-6xl">
                  Danial Zahidi
                </h2>
                <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
                  Frontend developer
                </h3>
                <p className="text-md py-5 leading-8 text-gray-700 md:text-xl max-w-xl">
                  Seeking a Junior Frontend Developer position to utilize my
                  skills and contribute to the team while learning from the
                  industry-software company.
                </p>
              </div>
            </div>
            <div className="text-5xl flex justify-center text-gray-600 gap-12 py-3">
              <Link href={""}><AiFillLinkedin /></Link>
              <Link target={"_blank"} className="" href={"https://github.com/danialzahidi15"}><AiFillGithub /></Link>
            </div>

            <Modal />
          </section>
        </main>
      </div>
    </>
  );
}
