import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import React, { useEffect, useState } from "react";
import Modal from "./modal";
import Link from "next/link";
import createClient from "./client";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [postData, setPost] = useState<any[]>([]);

  useEffect(() => {
    createClient
      .fetch(
        `*[_type == "post"]{
      title,
      slug,
      position,
      description,
    }`
      )
      .then((data) => setPost(data))
      .catch(console.error);
  }, []);

  const handleDarkMode = () => {
    setDarkMode(!darkMode);
  };

  return (
    <>
      <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Danial Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="bg-gray-100 mx-auto dark:bg-black">
          <section className="">
            <nav className="py-5 flex items-center justify-between px-4 md:px-10 bg-slate-700 dark:bg-black">
              <h1 className="text-xl font-mono dark:text-gray-400">
                thisis<span className="text-red-500">danial</span>
              </h1>
              <div className="flex items-center space-x-4">
                <div>
                  <BsFillMoonStarsFill
                    onClick={handleDarkMode}
                    className="cursor-pointer text-2xl dark:text-white"
                  />
                </div>
                <Modal />
              </div>
            </nav>

            {postData &&
              postData.map((post) => (
                <div className="relative min-h-screen flex items-center justify-center">
                  <div className="p-5">
                    <h2 className="text-teal-600 font-medium text-5xl transition md:text-6xl">
                      {post.title}
                    </h2>
                    <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
                      {post.position}
                    </h3>
                    <p key={post} className="text-md py-5 leading-8 text-gray-700 md:text-xl max-w-xl">
                      {post.description}
                    </p>
                    <div className="text-5xl flex justify-center text-gray-600 gap-12 py-3">
                      <Link
                        target={"_blank"}
                        href={"https://www.linkedin.com/in/danialzahidi/"}
                      >
                        <AiFillLinkedin />
                      </Link>
                      <Link
                        target={"_blank"}
                        href={"https://github.com/danialzahidi15"}
                      >
                        <AiFillGithub />
                      </Link>
                    </div>
                  </div>
                </div>
              ))}
          </section>
        </main>
      </div>
    </>
  );
}
